### ISSUE TITLE
Improve output of cell annotation

### ISSUE THREAD

**Issue by agouy** [tercen/cell_annotation_operator#2]
* add p-value (1 - pv) to first output table
* output second table with .ci and label of most probable cell type. Exclude p-values above threshold specified in the settings (default: 0.05) before annotation. If nothing significant for a given cluster, label as "Unknown"

Maybe later: column with multiple cell types if many significant hits.

**Comment by agouy** [comment]
@lucaslelann There seems to be some sort of relation issue in the output:
![image](https://user-images.githubusercontent.com/10561155/199524921-abe46d14-f0bc-4d97-b83e-7dcd97556df9.png)

Are we expecting multiple values per cell for Nkcell mature?

**Comment by lucaslelann** [comment]
No, It is fixed.

The origin of this was a duplicate in the population name in the annotation file.
